
server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        encrypt:
            enabled: false
        git:
          uri: https://github.com/rafaelqleite/projetosjava/tree/master/microservicos-spring-cloud/
          search-paths: fornecedor